export const FETCH_LIST_ACCOUNT= "FETCH_LIST_ACCOUNT";

export const FETCH_ADD_NEW_LISTACCOUNT= "FETCH_ADD_NEW_LISTACCOUNT";

export const FETCH_UPDATE_LISTACCOUNT= "FETCH_UPDATE_LISTACCOUNT";

export const FETCH_DELETE_LIST_ACCOUNT= "FETCH_DELETE_LIST_ACCOUNT";

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
