export const FETCH_LIST_ORDERDETAILS = "FETCH_LIST_ORDERDETAILS";

export const FETCH_ADD_NEW_ORDERDETAILS="FETCH_ADD_NEW_ORDERDETAILS";

export const FETCH_UPDATE_ORDERDETAILS="FETCH_UPDATE_ORDERDETAILS";

export const FETCH_DELETE_ORDERDETAILS="FETCH_DELETE_ORDERDETAILS";