export const FETCH_LIST_ORDER="FETCH_LIST_ORDER";

export const FETCH_ADD_NEW_ORDER="FETCH_ADD_NEW_ORDER";

export const FETCH_UPDATE_ORDER="FETCH_UPDATE_ORDER";

export const FETCH_DELETE_ORDER="FETCH_DELETE_ORDER";

