export const FETCH_LIST_PRODUCT= "FETCH_LIST_PRODUCT";

export const FETCH_ADD_NEW_LISTPRODUCT= "FETCH_ADD_NEW_LISTPRODUCT";

export const FETCH_UPDATE_LISTPRODUCT= "FETCH_UPDATE_LISTPRODUCT";

export const FETCH_DELETE_LIST_PRODUCT= "FETCH_DELETE_LIST_PRODUCT";

export const ACTION_GET_PRODUCT_BY_ID="ACTION_GET_PRODUCT_BY_ID";
