export const FETCH_LIST_PRODUCTPREVIEW= "FETCH_LIST_PRODUCTPREVIEW";

export const FETCH_ADD_NEW_LISTPRODUCTPREVIEW= "FETCH_ADD_NEW_LISTPRODUCTPREVIEW";

export const FETCH_UPDATE_LISTPRODUCTPREVIEW= "FETCH_UPDATE_LISTPRODUCTPREVIEW";

export const FETCH_DELETE_LIST_PRODUCTPREVIEW= "FETCH_UPDATE_LISTPRODUCTPREVIEW";
