export const ADD_TO_CART="ADD_TO_CART";

export const DELETE_ITEM_CART="DELETE_ITEM_CART";

export const DECREMENT="DECREMENT";

export const INCREMENT="INCREMENT";

export const DELETE_LIST_ITEM_CART="DELETE_LIST_ITEM_CART"