export const FETCH_LIST_PAYMENT= "FETCH_LIST_PAYMENT";

export const FETCH_ADD_NEW_LISTPAYMENT= "FETCH_ADD_NEW_LISTPAYMENT";

export const FETCH_UPDATE_LISTPAYMENT= "FETCH_UPDATE_LISTPAYMENT";

export const FETCH_DELETE_LIST_PAYMENT= "FETCH_DELETE_LIST_PAYMENT";
